name: gravity_gae_env
channels:
  - defaults
dependencies:
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - colorama==0.4.6
      - filelock==3.9.0
      - fsspec==2023.4.0
      - idna==3.4
      - jinja2==3.1.2
      - joblib==1.3.2
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.0
      - numpy==1.24.1
      - pandas==2.1.3
      - pillow==9.3.0
      - psutil==5.9.6
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - requests==2.28.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - six==1.16.0
      - sympy==1.12
      - threadpoolctl==3.2.0
      - torch==2.1.1+cu121
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2+pt21cu121
      - torch-sparse==0.6.18+pt21cu121
      - torchaudio==2.1.1+cu121
      - torcheval==0.0.7
      - torchvision==0.16.1+cu121
      - tqdm==4.66.1
      - typing-extensions==4.4.0
      - tzdata==2023.3
      - urllib3==1.26.13